USE master;
DROP DATABASE LIVRARIA_DB

CREATE DATABASE LIVRARIA_DB

USE LIVRARIA_DB

CREATE TABLE AUTORES (
	AUTOR_ID INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(150) NOT NULL,
	NACIONALIDADE VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATE,
	GENERO CHAR NOT NULL
);

CREATE TABLE LIVROS (
	LIVRO_ID INT PRIMARY KEY IDENTITY(1,1),
	TITULO VARCHAR(100) NOT NULL,
	AUTOR_ID INT NOT NULL,
	GENERO VARCHAR(100) NOT NULL,
	PRECO FLOAT NOT NULL CHECK (PRECO>0),
	QTD_ESTOQUE INT NOT NULL CHECK (QTD_ESTOQUE>=0),
	CONSTRAINT AUTOR_ID FOREIGN KEY (AUTOR_ID)
		REFERENCES AUTORES (AUTOR_ID)
		ON UPDATE CASCADE,
);

SELECT * FROM AUTORES WHERE AUTOR_ID = 1;